stats_item:
  name: "&f&lSTATS"
  material: "BOOK"
  lore:
    - "&7Spielzeit: &e%playtime% &7Min."
    - "&7Votes: &b%votes%"

items:
  claim_name: "&aBelohnung abholen"
  claimed_name: "&7Bereits abgeholt"
  locked_name: "&9Gesperrt"

levels:
  "1":
    required_playtime_minutes: 30
    required_votes: 1
    rewards:
      - "say %player% hat Level 1 Belohnung eingelöst!"
  "2":
    required_playtime_minutes: 120
    required_votes: 2
    rewards:
      - "say %player% hat Level 2 Belohnung eingelöst!"
  "3":
    required_playtime_minutes: 300
    required_votes: 3
    rewards:
      - "say %player% hat Level 3 Belohnung eingelöst!")
