gui:
  title: "&f&lLEVELS"
  rows: 6
  filled_item: "GRAY_STAINED_GLASS_PANE"
  stats_slot: 49

items:
  locked:
    material: LIGHT_BLUE_CANDLE
    name: "&9Noch nicht freigeschaltet"
  available:
    material: BLUE_CANDLE
    glow: true
    name: "&bKlicke zum Einlösen"
  claimed:
    material: LIGHT_GRAY_CANDLE
    name: "&7Bereits einglöst"

stats_item:
  material: BOOK
  name: "&f&lSTATS"
  lore:
    - "&7Spielzeit: &e%playtime% Minuten"
    - "&7Votes: &b%votes%"

levels:
  count: 45   # Anzahl der Level (egal ob 10, 20, 45, 100...)
